// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804192419_AddRuneEntity")]
    partial class AddRuneEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventParticipant", b =>
                {
                    b.Property<int>("AssistedId")
                        .HasColumnType("integer");

                    b.Property<int>("AssistingParticipantsId")
                        .HasColumnType("integer");

                    b.HasKey("AssistedId", "AssistingParticipantsId");

                    b.HasIndex("AssistingParticipantsId");

                    b.ToTable("EventAssists", (string)null);
                });

            modelBuilder.Entity("ItemParticipant", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantsId")
                        .HasColumnType("integer");

                    b.HasKey("ItemsId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("ParticipantItems", (string)null);
                });

            modelBuilder.Entity("MatchReferenceSummoner", b =>
                {
                    b.Property<int>("MatchReferencesId")
                        .HasColumnType("integer");

                    b.Property<int>("SummonersId")
                        .HasColumnType("integer");

                    b.HasKey("MatchReferencesId", "SummonersId");

                    b.HasIndex("SummonersId");

                    b.ToTable("MatchReferenceSummoner");
                });

            modelBuilder.Entity("ParticipantSummonerSpell", b =>
                {
                    b.Property<int>("ParticipantsId")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerSpellsId")
                        .HasColumnType("integer");

                    b.HasKey("ParticipantsId", "SummonerSpellsId");

                    b.HasIndex("SummonerSpellsId");

                    b.ToTable("ParticipantSummonerSpells", (string)null);
                });

            modelBuilder.Entity("backend.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiotId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("backend.Models.DataDragonState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DataDragonState");
                });

            modelBuilder.Entity("backend.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AfterItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("BeforeItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("Bounty")
                        .HasColumnType("integer");

                    b.Property<string>("BuildingType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("KillerParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("LaneType")
                        .HasColumnType("text");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("MonsterSubType")
                        .HasColumnType("text");

                    b.Property<string>("MonsterType")
                        .HasColumnType("text");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShutdownBounty")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TowerType")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VictimParticipantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AfterItemId");

                    b.HasIndex("BeforeItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("KillerParticipantId");

                    b.HasIndex("MatchId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("VictimParticipantId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("backend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SellPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("backend.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndOfGameResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GameDuration")
                        .HasColumnType("bigint");

                    b.Property<long>("GameEndTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("backend.Models.MatchReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MatchDbId")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QueueType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchDbId")
                        .IsUnique();

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchReferences");
                });

            modelBuilder.Entity("backend.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionId")
                        .HasColumnType("integer");

                    b.Property<int>("ChampionLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DamageToChampions")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Minions")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryRuneId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondaryTreeId")
                        .HasColumnType("integer");

                    b.Property<int>("SummonerId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("PrimaryRuneId");

                    b.HasIndex("SecondaryTreeId");

                    b.HasIndex("SummonerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("backend.Models.ParticipantFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentGold")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Minions")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalGold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ParticipantFrames");
                });

            modelBuilder.Entity("backend.Models.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SummonerId")
                        .HasColumnType("integer");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SummonerId");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("backend.Models.Rune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStyle")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiotId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Runes");
                });

            modelBuilder.Entity("backend.Models.Summoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.ToTable("Summoners");
                });

            modelBuilder.Entity("backend.Models.SummonerSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiotId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SummonerSpells");
                });

            modelBuilder.Entity("backend.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EventParticipant", b =>
                {
                    b.HasOne("backend.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("AssistedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("AssistingParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemParticipant", b =>
                {
                    b.HasOne("backend.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatchReferenceSummoner", b =>
                {
                    b.HasOne("backend.Models.MatchReference", null)
                        .WithMany()
                        .HasForeignKey("MatchReferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Summoner", null)
                        .WithMany()
                        .HasForeignKey("SummonersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParticipantSummonerSpell", b =>
                {
                    b.HasOne("backend.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.SummonerSpell", null)
                        .WithMany()
                        .HasForeignKey("SummonerSpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Event", b =>
                {
                    b.HasOne("backend.Models.Item", "AfterItem")
                        .WithMany("AfterEvents")
                        .HasForeignKey("AfterItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Item", "BeforeItem")
                        .WithMany("BeforeEvents")
                        .HasForeignKey("BeforeItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Item", "Item")
                        .WithMany("Events")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Participant", "Killer")
                        .WithMany("KillsAsKiller")
                        .HasForeignKey("KillerParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Participant", "Participant")
                        .WithMany("ParticipantInEvent")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Participant", "Victim")
                        .WithMany("DeathsAsVictim")
                        .HasForeignKey("VictimParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AfterItem");

                    b.Navigation("BeforeItem");

                    b.Navigation("Item");

                    b.Navigation("Killer");

                    b.Navigation("Match");

                    b.Navigation("Participant");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("backend.Models.MatchReference", b =>
                {
                    b.HasOne("backend.Models.Match", "Match")
                        .WithOne("MatchReference")
                        .HasForeignKey("backend.Models.MatchReference", "MatchDbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Match");
                });

            modelBuilder.Entity("backend.Models.Participant", b =>
                {
                    b.HasOne("backend.Models.Champion", "Champion")
                        .WithMany("Participants")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Rune", "PrimaryRune")
                        .WithMany()
                        .HasForeignKey("PrimaryRuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Rune", "SecondaryTree")
                        .WithMany()
                        .HasForeignKey("SecondaryTreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Summoner", "Summoner")
                        .WithMany()
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Team", "Team")
                        .WithMany("Participants")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");

                    b.Navigation("PrimaryRune");

                    b.Navigation("SecondaryTree");

                    b.Navigation("Summoner");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("backend.Models.ParticipantFrame", b =>
                {
                    b.HasOne("backend.Models.Participant", "Participant")
                        .WithMany("Frames")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("backend.Models.Queue", b =>
                {
                    b.HasOne("backend.Models.Summoner", "Summoner")
                        .WithMany("Queues")
                        .HasForeignKey("SummonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summoner");
                });

            modelBuilder.Entity("backend.Models.Team", b =>
                {
                    b.HasOne("backend.Models.Match", "Match")
                        .WithMany("Teams")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("backend.Models.Champion", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("backend.Models.Item", b =>
                {
                    b.Navigation("AfterEvents");

                    b.Navigation("BeforeEvents");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("backend.Models.Match", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("MatchReference")
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("backend.Models.Participant", b =>
                {
                    b.Navigation("DeathsAsVictim");

                    b.Navigation("Frames");

                    b.Navigation("KillsAsKiller");

                    b.Navigation("ParticipantInEvent");
                });

            modelBuilder.Entity("backend.Models.Summoner", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("backend.Models.Team", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
